config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'engine#params_entry'
  post '/params_entry', to: 'engine#generate'
  post '/results_performance', to: 'engine#results_performance'
  post '/results_positions', to: 'engine#results_positions'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/engine.rb
class Engine
  include ActiveModel::Model
  require 'date'

  attr_reader :parameters, :portfolio
  attr_accessor :rebalance_frequency, :market_cap_floor, :market_cap_ceiling, :initial_balance, :use_dual_momentum, :background, :test_run, :start_date, :single_period

  def initialize(parameters=nil)
    @parameters = parameters
  end

  def perform(parameters=nil, pusher_channel)
    @parameters = parameters

    @portfolio = Portfolio.new(
      position_count: parameters["position_count"],
      initial_balance: parameters["initial_balance"],
      start_date: parameters["start_date"],
      rebalance_frequency: parameters["rebalance_frequency"],
      pusher_channel: pusher_channel
    )

    PricePoint.all_periods(development: parameters['test_run'] == '1' ? true : false, single_period: parameters['single_period'], start_date: parameters['start_date']).each do |period|
      
      period = period.to_s
      Pusher.trigger(pusher_channel, 'update', { message: "Processing #{period} - ranking stocks" })
      
      current_market_data = ScoreCalculator.new(
        market_cap_floor: parameters["market_cap_floor"], 
        market_cap_ceiling: parameters["market_cap_ceiling"],
        period: period
      ).assign_scores

      Pusher.trigger(pusher_channel, 'update', { message: "Processing #{period} - building portfolio" })
      @portfolio.carry_forward(period) unless period == parameters["start_date"]
      target_portfolio = TargetPortfolio.new(
        current_portfolio_balance: @portfolio.as_of(period)[:total_market_value],
        position_count: @portfolio.position_count,
        current_market_data: current_market_data,
        parameters: parameters
        ).build(pusher_channel)
      @portfolio.rebalance(new_period: period, target: target_portfolio, parameters: parameters)
    end

    output = ReportGenerator.new(portfolio, parameters).generate(pusher_channel).to_json
    Result.all.destroy_all
    Result.create(result_string: output)
    Pusher.trigger(pusher_channel, 'update', { progress: 100, message: 'Done!' })
    self
  end
end

app/controllers/engine_controller.rb
class EngineController < ApplicationController
  respond_to :html, :js

  def params_entry
    @engine = Engine.new
  end

  def generate
    engine = Engine.new(get_params)
    if engine.valid?
      pusher_channel = 100
      engine.perform(get_params, pusher_channel)
      render file: "engine/results_link.js.erb"
    else
      render 'params_entry'
    end
  end

  def results_performance
    @source = JSON.parse(Result.last.result_string)
    respond_to do |format|
      format.html { render 'results_performance' }
      format.js { render 'results_performance' }
    end
  end

  def results_positions
   @source = JSON.parse(Result.last.result_string)
    respond_to do |format|
      format.html { render 'results_positions' }
      format.js { render 'results_positions' }
    end
  end

  private

  def get_params
    result = params.require(:engine).permit(:market_cap_floor, :market_cap_ceiling, :position_count, :initial_balance, :background, :rebalance_frequency, :test_run, :start_date, :single_period)
    result[:rebalance_frequency] = 'annual'
    result[:market_cap_floor] = nil if params[:engine][:market_cap_floor] == ''
    result[:market_cap_ceiling] = nil if params[:engine][:market_cap_ceiling] == ''
    result[:start_date] = params[:engine][:start_date] || '1993-12-31'
    result[:initial_balance] = params[:engine][:initial_balance].to_f
    result[:position_count] = params[:engine][:position_count].to_i
    result
  end
end

app/views/engine/_results_performance.html.haml
#content
  %ul.nav.nav-tabs
    %li.active
      = link_to 'View performance', results_performance_path, data: {method: :post, remote: true}
    %li
      = link_to 'View positions', results_positions_path, data: {method: :post, remote: true}
  %h3 Strategy Performance
  .voffset5
  %h4 Parameters
  .row
    .col-sm-5
      %table.table.table-condensed.table-borderless
        %tr
          %td Rebalance frequency
          %td.right-aligned annual
        %tr
          %td # of positions in portfolio
          %td.right-aligned= number_with_delimiter(@source['parameters']['position_count'])
        %tr
          %td Market cap floor, $mm
          %td.right-aligned= number_with_delimiter(@source['parameters']['market_cap_floor'])
        %tr
          %td Market cap ceiling, $mm
          %td.right-aligned= number_with_delimiter(@source['parameters']['market_cap_ceiling'])
  .voffset5
  %h4 By period
  %table.table.table-condensed
    %tr.table-header.blue-background
      %th{ rowspan: 2 } Period ending
      %th{ rowspan: 2 } Market value at period end
      %th{ colspan: 2 } by period
      %th{ colspan: 2 } by period, annualized
      %th{ colspan: 2 } cumulative calendar year
      %th{ colspan: 2 } rolling 12 months
    %tr.table-header.blue-background
      - 4.times do
        %th tested strategy
        %th S&P 500
    %tr.right-aligned
      %td.left-aligned
        %i Initial balance
      %td
        %i= number_to_currency(@source['parameters']['initial_balance'])
      - 8.times do
        %td
    - @source['performance'].each do |period|
      %tr.right-aligned
        %td.left-aligned= period['date']
        %td= number_to_currency(period['balance'])
        %td= pretty_percentage(period['by_period']['return'])
        %td= pretty_percentage(period['by_period']['sp500_return'])
        %td= pretty_percentage(period['annualized']['return'])
        %td= pretty_percentage(period['annualized']['sp500_return'])
        %td= pretty_percentage(period['cumulative_cy']['return'])
        %td= pretty_percentage(period['cumulative_cy']['sp500_return'])
        %td= pretty_percentage(period['rolling_12_months']['return'])
        %td= pretty_percentage(period['rolling_12_months']['sp500_return'])
  .voffset5
  %h4 Aggregated
  %p= "For the period between #{@source['aggregated']['start_date']} and #{@source['aggregated']['end_date']}"
  .voffset5
  .row
    .col-sm-7
      %table.table.table-condensed
        %tr.table-header.blue-background
          %th
          %th tested strategy
          %th S&P 500
        - @source['aggregated']['table'].each do |line, items|
          %tr.right-aligned
            %td.left-aligned= items['description']
            %td= line == 'e_sharpe' ? items['portfolio'] : pretty_percentage(items['portfolio'])
            %td= line == 'e_sharpe' ? items['sp500'] : pretty_percentage(items['sp500'])

app/views/engine/_results_positions.html.haml
#content
  %ul.nav.nav-tabs
    %li
      = link_to 'View performance', results_performance_path, data: {method: :post, remote: true}
    %li.active
      = link_to 'View positions', results_positions_path, data: {method: :post, remote: true}
  %h3 Holdings during each period
  - @source['positions'].each do |period|
    .voffset5
    %p.bold= period['end_date'] == '' ? "Current portfolio" : "Period ending #{period['end_date']}"
    %table.table.table-condensed.smaller-font.table-hover
      %tr.table-header.blue-background
        %th{ rowspan: 2 } Capital IQ ID
        %th{ rowspan: 2 } Company
        %th{ rowspan: 2 } Market cap
        %th{ rowspan: 2 } LTM EBIT
        %th{ rowspan: 2 } EV
        %th{ rowspan: 2 } Net PPE + NWC
        %th{ rowspan: 2 } Earnings yield
        %th{ rowspan: 2 } ROC
        %th{ rowspan: 2 } Shares
        %th{ colspan: 2 }= "as of #{period['start_date']}"
        %th{ colspan: 2 }= period['end_date'] == '' ? '' : "as of #{period['end_date']}"
        %th{ rowspan: 2 }= period['end_date'] == '' ? '' : 'Profit'
        %th{ rowspan: 2 } Notes
      %tr.table-header.blue-background
        %th Price per share
        %th Market value
        %th= period['end_date'] == '' ? '' : 'Price per share'
        %th= period['end_date'] == '' ? '' : 'Market value'
      - period['positions'].each do |position|
        %tr.right-aligned
          %td.left-aligned= position['cid']
          %td.left-aligned= position['company_name']
          %td= number_with_delimiter(position['market_cap'])
          %td= number_with_delimiter(position['ltm_ebit'])
          %td= number_with_delimiter(position['ev'])
          %td= number_with_delimiter(position['capital'])
          %td= pretty_percentage(position['earnings_yield'])
          %td= pretty_percentage(position['roc'])
          %td= number_with_delimiter(position['share_count'])
          %td= number_to_currency(position['beginning_price'])
          %td= number_to_currency(position['beginning_value'])
          %td= period['end_date'] == '' ? '' : number_to_currency(position['ending_price'])
          %td= period['end_date'] == '' ? '' : number_to_currency(position['ending_value'])
          %td= period['end_date'] == '' ? '' : number_to_currency(position['profit'], negative_format: "(%u%n)")
          %td= position['notes']
      %tr.right-aligned.italic
        %td.left-aligned Cash
        -9.times do
          %td
        %td= number_to_currency(period['cash'])
        %td
        %td= period['end_date'] == '' ? '' : number_to_currency(period['cash'])
        %td
        %td
      %tr.right-aligned.bold.blue-background
        %td.left-aligned Total
        - 9.times do
          %td
        %td= number_to_currency(period['total_value_beginning'])
        %td
        %td= period['end_date'] == '' ? '' : number_to_currency(period['total_value_ending'])
        %td= period['end_date'] == '' ? '' : number_to_currency(period['total_profit'], negative_format: "(%u%n)")
        %td

app/views/engine/params_entry.html.haml
= content_for :head do
  %script(type="text/javascript" src="http://js.pusher.com/2.1/pusher.min.js")

.container
  #content
    .row
      .col-sm-8.col-sm-offset-3
        %h3 Strategy parameters
        .voffset4
        = bootstrap_form_for @engine, url: '/params_entry', remote: true, layout: :horizontal, label_col: 'col-sm-4', control_col: 'col-sm-3' do |f|
          = f.text_field :position_count, label_class: "left-aligned", label: '# of positions in portfolio', value: '20'
          = f.select :rebalance_frequency, [['annual', 1], ['quarterly', 2], ['monthly', 3]], { label: 'Rebalance frequency'}
          = f.text_field :market_cap_floor, label: 'Market cap floor, $mm', value: 100
          = f.text_field :market_cap_ceiling, label: 'Market cap ceiling, $mm', value: 200
          = f.text_field :initial_balance, value: 1000000
          / = f.check_box :background, label: 'Execute in background (significant slowdown)'
          / = f.check_box :test_run, label: 'Test run (only 1993 through 2001)'
          / = f.text_field :start_date, value: '1993-12-31'
          / = f.check_box :single_period, label: 'One period only'
          .voffset4
          = f.submit 'Generate', class: "btn btn-primary btn-lg"
        .voffset4
        #progress-status
          %p.messages
        .voffset4
        #results-link-area

app/views/engine/results_link.js.erb
document.getElementById("results-link-area").innerHTML = "<%= j link_to 'View Results', results_performance_path, data: {method: :post, remote: true, params: {results: @results}}, id: 'results-link', class: "btn btn-success btn-lg" %>";

app/views/engine/results_performance.js.erb
$('#content').replaceWith("<%= j render 'engine/results_performance' %>");

app/views/engine/results_positions.js.erb
$('#content').replaceWith("<%= j render 'engine/results_positions' %>");

app/views/engine/status_update.js.erb
$('#progress-indicator').html("<%= @progress %>");